name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "practice-app"
      DOCKER_REPO: "maizmazin"
      TAG: "${{ github.run_id }}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_REPO/$IMAGE_NAME:$TAG .
          echo "Image built and tagged"

      - name: Push Docker Image
        run: |
          docker push $DOCKER_REPO/$IMAGE_NAME:$TAG
          echo "Image pushed to Docker Hub"

      - name: Deploy with Docker Compose
        env:
          DOCKER_REPO: ${{ env.DOCKER_REPO }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          TAG: ${{ env.TAG }}
        run: |
          docker-compose down
          docker-compose up -d
          echo "Deployment completed"
